config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :pins

root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC")

  end

  def show

  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save 
      redirect_to @pin, notice: "success!"
    else render 'new'
    end
  end

  def edit 

  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "success!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path

  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description)
  end

  def find_pin
    @pin = Pin.find{params[:id]}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5

%html
%head
  %title Joe-terest
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert alert-info"
  = yield


/ <!-- <!DOCTYPE html>
/ <html>
/ <head>
/   <title>PinBoard</title>
/   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
/   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
/   <%= csrf_meta_tags %>
/ </head>
/ <body>

/ <%= yield %>

/ </body>
/ </html>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Pin from saving
      %ul 
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, input_html: { class: 'form-control'}

  .form-group
    = f.input :description, input_html: { class: 'form-control'}

  = f.button :submit, class: "btn btn-primary"

      

app/views/pins/edit.html.haml
%h1 Edit Pin

= render 'form'

= link_to "cancel", pin_path

app/views/pins/index.html.haml
= link_to "New Pin", new_pin_path
- @pins.each do |pin|
  %h2= link_to pin.title, pin

app/views/pins/new.html.haml
%h1 new form

= render 'form'

= link_to "back", root_path

app/views/pins/show.html.haml
%h1= @pin.title
%p= @pin.description
%p 
Submitted by
= @pin.user.email

%br/


= link_to "back", root_path
= link_to "edit", edit_pin_path
= link_to "delete", pin_path, method: :delete, data: { confirm: "are you sure?" }